import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { ShieldAlert, Trash2, Eye } from "lucide-react";
import { useLanguage } from "../context/LanguageContext.jsx";
import { fetchAnalyses, deleteAnalysis, deleteAllAnalyses } from "../services/admin.js";

export default function AdminAnalyses() {
  const { lang } = useLanguage();
  const [loading, setLoading] = useState(true);
  const [analyses, setAnalyses] = useState([]);

  useEffect(() => {
    loadAnalyses();
  }, []);

  async function loadAnalyses() {
    try {
      const data = await fetchAnalyses();
      setAnalyses(data);
    } catch (error) {
      toast.error(error.message);
    } finally {
      setLoading(false);
    }
  }

  async function handleDelete(id) {
    if (!window.confirm(lang === "ar" ? "هل أنت متأكد من حذف هذا التحليل؟" : "Are you sure you want to delete this analysis request?")) {
      return;
    }
    try {
      await deleteAnalysis(id);
      toast.success(lang === "ar" ? "تم حذف التحليل بنجاح" : "Analysis request deleted successfully");
      loadAnalyses();
    } catch (error) {
      toast.error(error.message);
    }
  }

  async function handleDeleteAll() {
    if (!window.confirm(lang === "ar" ? "هل أنت متأكد من حذف كافة تحليلات المستخدمين نهائياً؟" : "Are you sure you want to delete ALL analysis requests permanently?")) {
      return;
    }
    try {
      await deleteAllAnalyses();
      toast.success(lang === "ar" ? "تم حذف جميع التحليلات بنجاح" : "All analysis requests deleted successfully");
      loadAnalyses();
    } catch (error) {
      toast.error(error.message);
    }
  }

  if (loading) return <div className="panel"><p>{lang === "ar" ? "جار تحميل التحليلات..." : "Loading analyses..."}</p></div>;

  return (
    <section className="panel admin-dashboard">
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "20px", flexWrap: "wrap", gap: "12px" }}>
        <div className="panel-title" style={{ margin: 0 }}>
          <ShieldAlert size={18} />
          <h2>{lang === "ar" ? "إدارة تحليلات المباريات" : "Match Analyses Management"}</h2>
        </div>
        {analyses.length > 0 && (
          <button
            className="danger-btn"
            type="button"
            onClick={handleDeleteAll}
            style={{
              padding: "8px 16px",
              fontSize: "0.85rem",
              fontWeight: "bold",
              display: "inline-flex",
              alignItems: "center",
              gap: "8px"
            }}
          >
            <Trash2 size={14} />
            {lang === "ar" ? "حذف الكل" : "Delete All"}
          </button>
        )}
      </div>

      <p style={{ color: "var(--muted)", marginBottom: "20px" }}>
        {lang === "ar"
          ? "تعرض هذه الصفحة كافة تحليلات Stockfish التي طلبها اللاعبون لمبارياتهم. يمكنك مراجعتها وحذفها من قاعدة البيانات."
          : "This page shows all Stockfish analysis requests generated by users. You can review and delete them from the database."}
      </p>

      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>{lang === "ar" ? "المستخدم" : "User"}</th>
              <th>{lang === "ar" ? "المباراة" : "Match"}</th>
              <th>{lang === "ar" ? "التاريخ" : "Requested At"}</th>
              <th>{lang === "ar" ? "إجراءات" : "Actions"}</th>
            </tr>
          </thead>
          <tbody>
            {analyses.map((analysis) => (
              <tr key={analysis.id}>
                <td data-label="ID">#{analysis.id}</td>
                <td data-label={lang === "ar" ? "المستخدم" : "User"}>
                  <div style={{ display: "flex", flexDirection: "column" }}>
                    <strong style={{ color: "var(--text)" }}>{analysis.username || (lang === "ar" ? "مستخدم غير معروف" : "Unknown User")}</strong>
                    <span style={{ fontSize: "0.75rem", color: "var(--muted)" }}>{analysis.email}</span>
                  </div>
                </td>
                <td data-label={lang === "ar" ? "المباراة" : "Match"}>
                  <div style={{ display: "flex", flexDirection: "column" }}>
                    <span>Match #{analysis.match_id}</span>
                    <span style={{ fontSize: "0.75rem", color: "var(--accent)" }}>
                      {analysis.result ? analysis.result.replace("_", " ") : (lang === "ar" ? "مكتملة" : "Completed")}
                    </span>
                  </div>
                </td>
                <td data-label={lang === "ar" ? "التاريخ" : "Requested At"}>
                  {analysis.requested_at ? new Date(analysis.requested_at).toLocaleDateString() : "-"}
                </td>
                <td data-label={lang === "ar" ? "إجراءات" : "Actions"}>
                  <div style={{ display: "flex", gap: "10px", flexWrap: "wrap" }}>
                    <a
                      href={`/game/match/${analysis.match_id}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="primary as-link"
                      style={{
                        padding: "6px 12px",
                        fontSize: "0.82rem",
                        display: "inline-flex",
                        alignItems: "center",
                        gap: "6px",
                        textDecoration: "none"
                      }}
                    >
                      <Eye size={14} />
                      {lang === "ar" ? "عرض" : "View"}
                    </a>
                    <button
                      className="danger-btn"
                      type="button"
                      onClick={() => handleDelete(analysis.id)}
                      style={{
                        padding: "6px 12px",
                        fontSize: "0.82rem",
                        display: "inline-flex",
                        alignItems: "center",
                        gap: "6px"
                      }}
                    >
                      <Trash2 size={14} />
                      {lang === "ar" ? "حذف" : "Delete"}
                    </button>
                  </div>
                </td>
              </tr>
            ))}
            {analyses.length === 0 && (
              <tr>
                <td colSpan="5" style={{ textAlign: "center", padding: "20px", color: "var(--muted)" }}>
                  {lang === "ar" ? "لا توجد طلبات تحليل مسجلة بعد" : "No analysis requests logged yet"}
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
}
