import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const translations = {
  en: {
    dashboard: "Dashboard",
    matchmaking: "Matchmaking",
    history: "Match History",
    leaderboard: "Leaderboard",
    profile: "Profile",
    logout: "Logout",
    boardThemes: "Board Themes",
    heroTitle: "Find a rival and play rated chess in real time.",
    heroSubtitle: "Moves are validated by chess.js, synchronized over Socket.IO, and saved to your match history.",
    vsPlayer: "vs Player",
    vsAI: "vs AI",
    yourElo: "Your Elo",
    online: "Online",
    mode: "Mode",
    rules: "Rules",
    rapid: "Rapid",
    rated: "Rated",
    onlinePlayers: "Online Players",
    readyNextGame: "Ready for your next game?",
    searchingOpponent: "Searching for an opponent...",
    pairingUsesQueue: "Pairing uses the active online queue. Open another browser session with a second account to test locally.",
    findMatch: "Find Match",
    inQueue: "In Queue",
    gameRoom: "Game Room",
    liveMatch: "Live Match",
    tacticsBoard: "Tactical Pulse",
    tacticsBoardCopy: "Watch the next forcing line, track the tempo, and jump into a game when the board is hot.",
    opponent: "Opponent",
    you: "You",
    turn: "Turn",
    white: "White",
    black: "Black",
    waiting: "Waiting",
    lastMove: "Last Move",
    showLastMove: "Show Last Move",
    check: "Check",
    resign: "Resign",
    movesHistory: "Moves History",
    movesWillAppear: "Moves will appear here.",
    topPlayersRanked: "The top arena chess players ranked by their Elo rating.",
    player: "Player",
    rating: "Rating",
    reviewPastMatches: "Review your past matches and rating outcomes.",
    result: "Result",
    ratingChange: "Rating Change",
    date: "Date",
    won: "Won",
    lost: "Lost",
    draw: "Draw",
    na: "N/A",
    manageAccountDetails: "Manage your account details and avatar.",
    username: "Username",
    currentElo: "Current Elo",
    updateAvatar: "Update Avatar",
    enterImageUrl: "Enter image URL",
    update: "Update",
    login: "Login",
    register: "Register",
    password: "Password",
    signIn: "Sign In",
    signUp: "Sign Up",
    dontHaveAccount: "Don't have an account? Sign up",
    alreadyHaveAccount: "Already registered? Login",
    language: "Language",
    languageName: "English",
    rapid10m: "10 minute rapid",
    startAt0Elo: "Start at 0 Elo and climb the global leaderboard.",
    email: "Email",
    avatarUrl: "Avatar URL",
    creating: "Creating...",
    welcomeBack: "Welcome back!",
    enterCredentials: "Enter your credentials to access the arena.",
    createAccount: "Create your account",
    invite: "Invite Friend",
    inviteTitle: "Invite a Friend",
    inviteDescription: "Enter your friend’s 6-digit player ID to invite them to a game:",
    inviteYourId: "Your player ID",
    inviteTargetLabel: "Friend's player ID",
    inviteEnterId: "Enter 6-digit ID",
    inviteSend: "Send Invite",
    admin: "Admin",
    sendNotification: "Send Notification",
    createTournament: "Create Tournament",
    openReports: "Open Reports",
    inviteReceivedTitle: "Game Invite",
    inviteReceivedText: "You have received a game invite from",
    inviteAccepted: "Invite accepted! Joining game...",
    inviteRejected: "Invite rejected",
    inviteCanceled: "Invite canceled",
    inviteLink: "Player ID",
    copy: "Copy",
    linkCopied: "Player ID copied!",
    tournaments: "Tournaments",
    joined: "Joined",
    join: "Join",
    participants: "Participants",
    maxParticipants: "Max players",
    logoUrl: "Logo URL",
    styleColor: "Style color",
    endsAt: "Ends at",
    scheduleMatch: "Schedule match",
    whitePlayer: "White player",
    blackPlayer: "Black player",
    scheduledTime: "Match time",
    createNewTournament: "Create tournament",
    updateTournament: "Update tournament",
    deleteTournament: "Delete tournament",
    selectTournament: "Select a tournament to edit",
    noTournaments: "No tournaments available right now.",
    events: "Events",
    active: "Active",
    upcoming: "Upcoming",
    footerRights: "All rights reserved © 2026",
    footerCreatedBy: "The game was made by",
    footerPortfolio: "Portfolio"
  },
  ar: {
    dashboard: "لوحة التحكم",
    matchmaking: "البحث عن مباراة",
    history: "سجل المباريات",
    leaderboard: "المتصدرون",
    profile: "الملف الشخصي",
    logout: "تسجيل الخروج",
    boardThemes: "ألوان الرقعة",
    heroTitle: "ابحث عن منافس والعب شطرنج مصنف في الوقت الحقيقي.",
    heroSubtitle: "يتم التحقق من النقلات بواسطة chess.js، ومزامنتها عبر Socket.IO، وحفظها في سجل مبارياتك.",
    vsPlayer: "ضد لاعب",
    vsAI: "ضد AI",
    yourElo: "تقييمك",
    online: "متصل",
    mode: "النمط",
    rules: "القواعد",
    rapid: "سريع",
    rated: "مصنف",
    onlinePlayers: "اللاعبون المتصلون",
    readyNextGame: "جاهز لمباراتك القادمة؟",
    searchingOpponent: "جار البحث عن خصم...",
    pairingUsesQueue: "يعتمد البحث على قائمة الانتظار النشطة. افتح جلسة متصفح أخرى بحساب ثان للتجربة محليا.",
    findMatch: "ابحث عن مباراة",
    inQueue: "في الانتظار",
    gameRoom: "غرفة اللعب",
    liveMatch: "مباراة مباشرة",
    tacticsBoard: "نبض تكتيكي",
    tacticsBoardCopy: "تابع الخط القادم، راقب الإيقاع، وادخل المباراة عندما تسخن الرقعة.",
    opponent: "الخصم",
    you: "أنت",
    turn: "الدور",
    white: "الأبيض",
    black: "الأسود",
    waiting: "انتظار",
    lastMove: "الحركة الأخيرة",
    showLastMove: "عرض الحركة الأخيرة",
    check: "كش",
    resign: "انسحاب",
    movesHistory: "سجل النقلات",
    movesWillAppear: "ستظهر النقلات هنا.",
    topPlayersRanked: "أفضل لاعبي الساحة مرتبين حسب تقييم Elo.",
    player: "اللاعب",
    rating: "التقييم",
    reviewPastMatches: "راجع مبارياتك السابقة ونتائج تقييمك.",
    result: "النتيجة",
    ratingChange: "تغير التقييم",
    date: "التاريخ",
    won: "فوز",
    lost: "خسارة",
    draw: "تعادل",
    na: "غير متاح",
    manageAccountDetails: "إدارة تفاصيل حسابك وصورتك.",
    username: "اسم المستخدم",
    currentElo: "التقييم الحالي",
    updateAvatar: "تحديث الصورة",
    enterImageUrl: "أدخل رابط الصورة",
    update: "تحديث",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    password: "كلمة المرور",
    signIn: "دخول",
    signUp: "تسجيل",
    dontHaveAccount: "ليس لديك حساب؟ سجل الآن",
    alreadyHaveAccount: "لديك حساب بالفعل؟ سجل دخولك",
    language: "اللغة",
    languageName: "العربية",
    rapid10m: "شطرنج سريع 10 دقائق",
    startAt0Elo: "ابدأ بتقييم 0 Elo واصعد في قائمة المتصدرين العالمية.",
    email: "البريد الإلكتروني",
    avatarUrl: "صورة اللاعب",
    creating: "جار الإنشاء...",
    welcomeBack: "مرحبا بعودتك!",
    enterCredentials: "أدخل بياناتك للدخول إلى الساحة.",
    createAccount: "أنشئ حسابك",
    invite: "دعوة صديق",
    inviteTitle: "دعوة صديق",
    inviteDescription: "أدخل معرف اللاعب المكون من 6 أرقام لصديقك لدعوته للعب:",
    inviteYourId: "معرف اللاعب الخاص بك",
    inviteTargetLabel: "معرف لاعب الصديق",
    inviteEnterId: "أدخل معرف من 6 أرقام",
    inviteSend: "أرسل الدعوة",
    admin: "لوحة الأدمن",
    tournamentManagement: "إدارة البطولات",
    sendNotification: "إرسال إشعار",
    createTournament: "إنشاء بطولة",
    openReports: "التقارير",
    inviteReceivedTitle: "طلب لعبة",
    inviteReceivedText: "لديك طلب لعب من",
    inviteAccepted: "تم قبول الدعوة! جاري الانضمام...",
    inviteRejected: "تم رفض الدعوة",
    inviteCanceled: "تم إلغاء الدعوة",
    inviteLink: "معرف اللاعب",
    copy: "نسخ",
    linkCopied: "تم نسخ معرف اللاعب!",
    tournaments: "البطولات",
    joined: "منضم",
    join: "انضم",
    participants: "مشترك",
    maxParticipants: "أقصى عدد لاعبين",
    logoUrl: "رابط الشعار",
    styleColor: "لون البطولة",
    endsAt: "تنتهي في",
    scheduleMatch: "جدولة مباراة",
    whitePlayer: "لاعب الأبيض",
    blackPlayer: "لاعب الأسود",
    scheduledTime: "ميعاد المباراة",
    createNewTournament: "إنشاء بطولة جديدة",
    updateTournament: "تحديث البطولة",
    deleteTournament: "حذف البطولة",
    selectTournament: "اختر بطولة للتعديل",
    noTournaments: "لا توجد بطولات متاحة حالياً.",
    events: "الفعاليات",
    active: "نشط",
    upcoming: "قادم",
    footerRights: "كل الحقوق محفوظة © 2026",
    footerCreatedBy: "العبة اتعملت بواسطة",
    footerPortfolio: "بورتفوليو"
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem("gca_lang") || "ar");

  useEffect(() => {
    localStorage.setItem("gca_lang", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  const value = useMemo(
    () => ({
      lang,
      setLang,
      t: (key) => translations[lang]?.[key] || key,
      isRtl: lang === "ar"
    }),
    [lang]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
